Repository prgrms-web-devcourse/Team-6Jeans-Hype-BE, pull requests merged in 2023-03, with the labels that each got.

#108 [FEAT] 대결 결과 산정 스케줄러 기능 구현
  build.gradle
  codecov.yml
  src/main/java/com/example/demo/controller/SchedulerController.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/battle/BattleInfo.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/member/MemberScore.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/main/java/com/example/demo/service/MemberService.java
  src/test/java/com/example/demo/model/battle/BattleInfoTest.java
  src/test/java/com/example/demo/model/battle/BattleTest.java
  src/test/java/com/example/demo/model/member/MemberScoreTest.java
  src/test/java/com/example/demo/model/member/MemberTest.java
  src/test/java/com/example/demo/repository/BattleRepositoryTest.java
  src/test/java/com/example/demo/service/BattleServiceTest.java
  src/test/java/com/example/demo/service/MemberServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#111 [ADD] 대결가능한 추천글 등록할 경우 작성자에게 도전권 부여 기능 추가
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, TEST, ADD

#114 [ADD] Post - Member 연관관계 편의 메소드 추가 및 적용
  src/main/java/com/example/demo/model/post/Post.java
Labels: 리뷰 요청, 백엔드, sohyeon, ADD

#121 [ADD] 대결 후보 곡 조회: musicUrl 추가
  src/main/java/com/example/demo/dto/post/PostBattleCandidateMusicResponseDto.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, TEST, ADD

#118 [FEAT] 대결 상세 정보 리스트 조회(숏폼 리스트)
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/dto/battle/BattleDetailsListResponseDto.java
  src/main/java/com/example/demo/dto/battle/BattleDetailsResponseDto.java
  src/main/java/com/example/demo/dto/battle/BattlePostResponseVo.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListIntegrationTest.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#123 [FEAT] 유저가 참여한 대결 리스트 조회 기능 구현 및 테스트
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/GenreController.java
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/dto/member/MemberBattleGenreVO.java
  src/main/java/com/example/demo/dto/member/MemberBattlePostVO.java
  src/main/java/com/example/demo/dto/member/MemberBattleResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberBattlesResponseDto.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/MemberService.java
  src/test/java/com/example/demo/controller/MemberControllerTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllIntegrationTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/MemberServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#122 [FEAT] 대결곡 투표
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/dto/battle/BattlePostResponseVo.java
  src/main/java/com/example/demo/dto/common/MusicVoResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberPostVoResponseDto.java
  src/main/java/com/example/demo/dto/vote/BattleVoteRequestDto.java
  src/main/java/com/example/demo/dto/vote/VoteResultResponseDto.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/battle/BattleInfo.java
  src/main/java/com/example/demo/model/battle/BattleVotedResult.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/repository/VoteRepository.java
  src/main/java/com/example/demo/service/VoteService.java
  src/test/java/com/example/demo/controller/TestUtil.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListIntegrationTest.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListRestDocsTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllIntegrationTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
  src/test/java/com/example/demo/controller/vote/BattleVoteIntegrationTest.java
  src/test/java/com/example/demo/controller/vote/BattleVoteRestDocsTest.java
  src/test/java/com/example/demo/model/battle/BattleTest.java
  src/test/java/com/example/demo/repository/BattleRepositoryTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#128 [FIX] 필드명 변경: musicName -> title
  src/main/java/com/example/demo/dto/post/PostBattleCandidateMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostCreateRequestDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostFindMusicResponseDto.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FIX

#129 [FIX] 마이페이지/유저페이지 분리 및 limit, 장르 필터링 기능을 위한 수정.
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/dto/member/MemberAllMyPostsResponseDto.java
  src/main/java/com/example/demo/exception/ServerNotActiveException.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/MemberFilteringCase.java
  src/main/java/com/example/demo/service/MemberService.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#130 [FEAT] 대결 신청 API 기능 추가 + 통합테스트 작성
  .github/workflows/pr-check.yml
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/dto/battle/BattleCreateRequestDto.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/main/resources/db/migration/V2.2__Delete_Battle_Member_relation.sql
  src/test/java/com/example/demo/controller/BattleControllerTest.java
  src/test/java/com/example/demo/controller/TestUtil.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/MemberServiceTest.java
Labels: 리뷰 요청, 백엔드, sejun, FEAT, high

#134 [ADD] 대결 투표 기능에서 이미 투표한 배틀의 경우 에 대한 예외 추가.
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/repository/VoteRepository.java
  src/main/java/com/example/demo/service/VoteService.java
Labels: 리뷰 요청, 백엔드, suyoung, ADD

#132 [FIX] 대결 숏폼 리스트 조회 시 유저가 투표한 리스트는 나오지 않게 수정.
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/model/battle/Vote.java
  src/main/java/com/example/demo/repository/VoteRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListIntegrationTest.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#143 [FIX] 참여한 대결 리스트 응답 데이터 수정
  src/main/java/com/example/demo/dto/member/MemberBattlePostVO.java
  src/test/java/com/example/demo/controller/MemberControllerTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#137 [ADD] 추천글 리스트 조회: 최신순 정렬 추가
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/dto/post/PostsFindResponseDto.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, ADD

#147 [FEAT] #90, #91 대결id로 상세조회, 대결 리스트 조회 기능 구현
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/dto/battle/BattleDetailByIdResponseDto.java
  src/main/java/com/example/demo/dto/battle/BattleInfoVo.java
  src/main/java/com/example/demo/dto/battle/BattlePostInfoWithVoteCntResponseVo.java
  src/main/java/com/example/demo/dto/battle/BattlesResponseDto.java
  src/main/java/com/example/demo/dto/music/SimpleMusicInfoVo.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/BattleControllerTest.java
Labels: 리뷰 요청, 백엔드, sejun, FEAT, TEST

#150 [CHORE] 문서화 수정
  src/test/java/com/example/demo/controller/BattleControllerTest.java
Labels: CHORE

#156 [FEAT] 추천글 좋아요 기능 구현 및 테스트
  build.gradle
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/config/RedisConfig.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostLikeResponseDto.java
  src/main/java/com/example/demo/model/post/Post.java
  src/main/java/com/example/demo/repository/LikeRepository.java
  src/main/java/com/example/demo/service/PostLockFacade.java
  src/main/java/com/example/demo/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/service/PostLikeTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#160 [FEAT] 유저 닉네임 수정 및 프로필 이미지 수정.
  build.gradle
  src/main/java/com/example/demo/common/AmazonS3ResourceStorage.java
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/common/ResourceStorage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/config/AwsS3Config.java
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/dto/member/MemberNicknameUpdateRequestDto.java
  src/main/java/com/example/demo/dto/member/MemberUpdateResponseDto.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/service/MemberService.java
  src/main/java/com/example/demo/util/FileFormat.java
  src/main/java/com/example/demo/util/MultipartUtil.java
  src/main/resources/application-resource-path.yml
  src/main/resources/application.yml
  src/test/java/com/example/demo/controller/battle/BattleDetailsListIntegrationTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
  src/test/java/com/example/demo/controller/member/MemberUpdateRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberUpdateTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#162 [ADD] 유저 참여 대결 리스트 조회: isWin 데이터 추가
  src/main/java/com/example/demo/dto/member/MemberBattlePostVO.java
  src/main/java/com/example/demo/dto/member/MemberBattleResponseDto.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/test/java/com/example/demo/controller/MemberControllerTest.java
  src/test/java/com/example/demo/service/MemberServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, ADD

#171 [FIX] 유저 참여 대결 조회: index 초과 에러 해결
  src/main/java/com/example/demo/service/MemberService.java
Labels: 리뷰 요청, 백엔드, sohyeon, FIX

#164 [FIX] 추천곡 후보 리스트 조회: 로그온 유저와 대결신청 추천곡 작성자와 같을 때의 예외로직 추가
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostsBattleCandidateResponseDto.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FIX, TEST, ADD

#168 [FEAT] 추천글 좋아요 상위 10개 조회 기능 구현 및 테스트
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#179 [FIX] 스케줄러 변경: 승리포인트 업데이트 비활성화
  src/main/java/com/example/demo/controller/SchedulerController.java
  src/main/java/com/example/demo/service/BattleService.java
Labels: sohyeon, HOTFIX

#181 [FIX] 스케줄러 시간 변경: 0시
  src/main/java/com/example/demo/controller/SchedulerController.java
Labels: HOTFIX

#174 [FEAT] 유저 랭킹 리스트 조회 구현 및 통합 테스트 작성
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/constant/RankingConstant.java
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/controller/SchedulerController.java
  src/main/java/com/example/demo/dto/battle/BattleDetailByIdResponseDto.java
  src/main/java/com/example/demo/dto/ranking/DateInfoForRankingVo.java
  src/main/java/com/example/demo/dto/ranking/RankerInfoVo.java
  src/main/java/com/example/demo/dto/ranking/RankersResponseDto.java
  src/main/java/com/example/demo/repository/MemberRepository.java
  src/main/java/com/example/demo/service/MemberService.java
  src/test/java/com/example/demo/controller/MemberControllerRankingTest.java
  src/test/java/com/example/demo/repository/MemberRepositoryTest.java
Labels: 백엔드, sejun, FEAT

#187 [FIX] 대결 산정 날짜 변경: 하루 전
  src/main/java/com/example/demo/service/BattleService.java
Labels: sohyeon, HOTFIX

#184 유저 대결 상세 페이지 pr 에 대한 수정 제안. sejun_pr_#167 -> suyong_ #167
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/dto/battle/BattleDetailByIdResponseDto.java
  src/main/java/com/example/demo/repository/VoteRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/main/java/com/example/demo/service/PrincipalService.java
  src/test/java/com/example/demo/controller/BattleControllerTest.java
Labels: 리뷰 요청, 백엔드, sejun, suyoung, REFACTOR

#182 [ADD] 같은 post 들에 대한 진행 중인 대결이 있을 경우 대결 생성이 되지 않도록 코드 추가
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/BattleControllerTest.java
  src/test/java/com/example/demo/controller/MemberControllerRankingTest.java
  src/test/java/com/example/demo/repository/BattleRepositoryTest.java
Labels: 리뷰 요청, 백엔드, sejun, ADD, low

#189 [ADD] 스케줄러 플러시 추가
  src/main/java/com/example/demo/controller/SchedulerController.java
Labels: sohyeon, HOTFIX

#191 [FIX] 스케줄러 시간 자정으로 변경
  src/main/java/com/example/demo/controller/SchedulerController.java
Labels: sohyeon, HOTFIX

#194 [FIX] 좋아요 상위 추천글 리스트 조회: 쿼리 변경 최적화
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FIX

#185 [FEAT] 마이페이지 - 유저가 좋아요한 게시글 조회 기능 추가
  src/main/java/com/example/demo/common/AmazonS3ResourceStorage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/exception/ServerNotActiveException.java
  src/main/java/com/example/demo/exception/ServerNotExecuteException.java
  src/main/java/com/example/demo/model/post/Like.java
  src/main/java/com/example/demo/repository/LikeRepository.java
  src/main/java/com/example/demo/service/MemberService.java
  src/main/java/com/example/demo/util/MultipartUtils.java
  src/main/resources/application-test.yml
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
  src/test/java/com/example/demo/controller/member/MemberLikePostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberLikePostsTest.java
  src/test/java/com/example/demo/controller/member/MemberUpdateTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#196 [FIX] 유저페이지 형태로의 api 호출에서도 나의 정보가 보이는 문제 수정
  src/main/java/com/example/demo/controller/MemberController.java
  src/main/java/com/example/demo/service/MemberService.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#200 [FEAT] 좋아요 여부 판단 기능 구현 및 테스트
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostIsLikeResponseDto.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#198 [FEAT] 메인 페이지 랜덤한 배틀 정보 조회 기능
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/BattleController.java
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/battle/BattleRamdomTest.java
  src/test/java/com/example/demo/controller/battle/BattleRandomRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#205 [HOTFIX] 추천 게시글 상세조회에서 내려주는 데이터에 memberId 추가.
  src/main/java/com/example/demo/dto/post/PostDetailFindResponseDto.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
Labels: 백엔드, suyoung, HOTFIX

#207 [FEAT] 애플뮤직 API로 음악 검색 키워드를 받아서 대신 요청하는 API 추가.
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/MusicController.java
  src/main/java/com/example/demo/service/ItunesMusicSearchService.java
  src/main/java/com/example/demo/service/MusicSearchService.java
  src/test/java/com/example/demo/controller/music/MusicSearchRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#209 [TEST] 음악 검색 api RestDocs에서 누락된 쿼리 파라미터 추가.
  src/test/java/com/example/demo/controller/music/MusicSearchRestDocsTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX, TEST

#202 [FIX] battle리스트 조회시 최신순 부터 조회하도록 변경
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
  src/test/java/com/example/demo/controller/BattleControllerTest.java
  src/test/java/com/example/demo/controller/battle/BattleDetailsListIntegrationTest.java
  src/test/java/com/example/demo/repository/BattleRepositoryTest.java
Labels: 리뷰 요청, 백엔드, sejun, FIX

#214 [FIX] 랜덤한 대결 뽑는 기능 로직 수정.
  src/main/java/com/example/demo/repository/BattleRepository.java
  src/main/java/com/example/demo/service/BattleService.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#216 [FIX] 음악 검색 api 내려줄 때 음악 재생 url이 존재하지 않는 경우 필터링 하도록 수정.
  src/main/java/com/example/demo/controller/MusicController.java
  src/main/java/com/example/demo/dto/music/MusicSearchResponseDto.java
  src/main/java/com/example/demo/dto/music/MusicSearchResponseVo.java
  src/main/java/com/example/demo/service/ItunesMusicSearchService.java
  src/main/java/com/example/demo/service/MusicSearchService.java
Labels: 리뷰 요청, 백엔드, suyoung, FIX

#220 [CHORE] release 브랜치로 배포.
  .github/workflows/deploy-release.yml
Labels: CHORE, suyoung

#222 [CHORE] 리팩토링을 위한 환경 설정.
  .github/workflows/deploy-release.yml
  .github/workflows/pr-check-release.yml
  src/main/resources/application.yml
Labels: CHORE, suyoung

#225 [CHORE] nginx를 이용하여 무중단 배포 구현 - 2
  scripts/deploy_no_stop.sh
  src/main/java/com/example/demo/controller/ProfileController.java
Labels: CHORE, suyoung

#226 [CHORE] nginx를 이용하여 무중단 배포 구현 - 3
  appspec.yml
  scripts/deploy_no_stop.sh
  src/main/java/com/example/demo/controller/ProfileController.java
  src/main/resources/application-prod.yml
  src/main/resources/application-prod2.yml
Labels: CHORE, suyoung

#228 [CHORE] 쉘 파일 수정.
  scripts/deploy_no_stop.sh
Labels: CHORE, suyoung
