Repository prgrms-web-devcourse/Team-6Jeans-Hype-BE, pull requests merged in 2023-02, with the labels that each got.

#9 [CHORE] CI 세팅
  .github/workflows/deploy.yml
Labels: 백엔드, CHORE, sohyeon

#14 [CHORE] CD 세팅
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
Labels: 백엔드, CHORE, sohyeon

#17 [CHORE] codecov 관련 설정
  .github/workflows/deploy.yml
  build.gradle
  codecov.yml
Labels: 백엔드, CHORE, suyoung

#12 [CHORE] 린트 설정, rest docs 설정
  .editorconfig
  .gitattributes
  .github/workflows/deploy.yml
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  naver-intellij-formatter.xml
  src/main/java/com/example/demo/Application.java
  src/main/java/com/example/demo/controller/HealthController.java
  src/main/lombok.config
  src/test/java/com/example/demo/controller/HealthControllerTest.java
Labels: 백엔드, CHORE, sejun

#29 [FIX] CICD 기능 분리
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  src/main/java/com/example/demo/controller/HealthController.java
  src/test/java/com/example/demo/controller/HealthControllerTest.java
Labels: 백엔드, sohyeon, FIX

#31 [FEAT] Entity 초기 설계
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  src/main/java/com/example/demo/controller/HealthController.java
  src/main/java/com/example/demo/model/Battle.java
  src/main/java/com/example/demo/model/Genre.java
  src/main/java/com/example/demo/model/Image.java
  src/main/java/com/example/demo/model/Member.java
  src/main/java/com/example/demo/model/Music.java
  src/main/java/com/example/demo/model/Post.java
  src/test/java/com/example/demo/ApplicationTests.java
  src/test/java/com/example/demo/controller/HealthControllerTest.java
Labels: 백엔드, suyoung, FEAT

#46 [FIX] checkstyle 관련 오류
  build.gradle
Labels: BUG

#32 [FEAT] Entity 초기 설계
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/example/demo/config/JpaAuditingConfig.java
  src/main/java/com/example/demo/model/BaseEntity.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/battle/BattleInfo.java
  src/main/java/com/example/demo/model/battle/Vote.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/member/MemberScore.java
  src/main/java/com/example/demo/model/member/Social.java
  src/main/java/com/example/demo/model/member/SocialInfo.java
  src/main/java/com/example/demo/model/post/Genre.java
  src/main/java/com/example/demo/model/post/Like.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/model/post/Post.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/example/demo/ApplicationTests.java
Labels: 백엔드, suyoung, FEAT

#44 [CHPRE] 공통 Response 파일 생성
  build.gradle
  src/main/java/com/example/demo/common/ApiResponse.java
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
Labels: 백엔드, CHORE, sohyeon

#54 [TEST] Member 패키지 엔티티 테스트
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/member/MemberScore.java
  src/main/java/com/example/demo/model/member/SocialInfo.java
  src/test/java/com/example/demo/model/member/MemberTest.java
Labels: 백엔드, sohyeon, TEST

#57 [FEAT] 플라이웨이 적용, test db docker compose 작성, 환경별 application.yml 분리
  .github/workflows/deploy.yml
  .gitignore
  localTestDB/conf.d/my.cnf
  localTestDB/docker-compose.yml
  scripts/deploy.sh
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
Labels: 백엔드, sejun, FEAT

#53 [TEST] Post 패키지 Entity 테스트
  src/main/java/com/example/demo/model/member/SocialInfo.java
  src/main/java/com/example/demo/model/post/Like.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/model/post/Post.java
  src/test/java/com/example/demo/model/post/LikeTest.java
  src/test/java/com/example/demo/model/post/PostTest.java
Labels: 백엔드, suyoung, TEST

#58 [TEST] 엔티티 테스트
  build.gradle
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/battle/BattleInfo.java
  src/main/java/com/example/demo/model/battle/Vote.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/member/MemberScore.java
  src/main/java/com/example/demo/model/member/SocialInfo.java
  src/main/java/com/example/demo/model/post/Like.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/model/post/Post.java
  src/test/java/com/example/demo/model/battle/BattleTest.java
  src/test/java/com/example/demo/model/battle/VoteTest.java
  src/test/java/com/example/demo/model/member/MemberTest.java
  src/test/java/com/example/demo/model/post/LikeTest.java
  src/test/java/com/example/demo/model/post/PostTest.java
Labels: 백엔드, sohyeon, sejun, suyoung, TEST

#59 [FEAT] 플라이웨이 적용, test db docker compose 작성, 환경별 application.yml 분리
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  .gitignore
  build.gradle
  localTestDB/conf.d/my.cnf
  localTestDB/docker-compose.yml
  scripts/deploy.sh
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
Labels: 백엔드, sejun, FEAT

#74 [FIX] jacoco 설정파일 수정.
  build.gradle
Labels: 백엔드, suyoung, FIX

#76 [FEAT] 유저 세부정보 조회 기능 및 테스트 코드 추가.
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/member/MemberController.java
  src/main/java/com/example/demo/dto/member/MemberDetailsResponseDto.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/repository/MemberRepository.java
  src/test/java/com/example/demo/controller/member/MemberControllerRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberControllerTest.java
  src/test/java/com/example/demo/controller/member/MemberTestUtil.java
  src/test/java/com/example/demo/model/post/LikeTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#72 [FEAT] 대결 후보곡 리스트 조회 구현 및 테스트
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateResponseDto.java
  src/main/java/com/example/demo/dto/post/PostsBattleCandidateResponseDto.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: sohyeon, FEAT, TEST

#71 [FEAT] 음악 공유 게시글 상세 조회 기능 구현 및 테스트
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateResponseDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindMusicGenreResponseDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindResponseDto.java
  src/main/java/com/example/demo/dto/post/PostsBattleCandidateResponseDto.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: sohyeon, FEAT, TEST

#75 [FEAT] 유저음악 공유 게시글 리스트 조회 기능 코드 추가.
  build.gradle
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/example/demo/controller/member/MemberController.java
  src/main/java/com/example/demo/dto/member/MemberAllMyPostsResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberPostVoResponseDto.java
  src/main/java/com/example/demo/dto/member/MusicVoResponseDto.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/service/MemberService.java
  src/main/java/com/example/demo/service/PrincipalService.java
  src/main/resources/application.yml
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
Labels: 백엔드, suyoung, FEAT

#63 [FEAT] 장르 전체 조회 기능 및 테스트 코드 추가
  build.gradle
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/controller/genre/GenreController.java
  src/main/java/com/example/demo/controller/member/MemberController.java
  src/main/java/com/example/demo/dto/genre/GenreAllResponseDto.java
  src/main/java/com/example/demo/dto/genre/GenreVoResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberAllMyPostsResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberDetailsResponseDto.java
  src/main/java/com/example/demo/dto/member/MemberPostVoResponseDto.java
  src/main/java/com/example/demo/dto/member/MusicVoResponseDto.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/model/post/Genre.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/repository/MemberRepository.java
  src/main/java/com/example/demo/service/MemberService.java
  src/main/java/com/example/demo/service/PrincipalService.java
  src/main/resources/application.yml
  src/test/java/com/example/demo/controller/genre/GenreAllIntegrationTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsTest.java
  src/test/java/com/example/demo/controller/member/MemberTestUtil.java
  src/test/java/com/example/demo/dto/genre/GenreAllResponseDtoTest.java
  src/test/java/com/example/demo/dto/genre/GenreVoResponseDtoTest.java
  src/test/java/com/example/demo/model/member/MemberTest.java
  src/test/java/com/example/demo/model/post/LikeTest.java
  src/test/java/com/example/demo/model/post/PostTest.java
Labels: 리뷰 요청, 백엔드, suyoung, FEAT

#68 [FEAT] 음악 공유 게시글 등록 및 전체 조회 기능 구현 및 테스트
  build.gradle
  src/main/java/com/example/demo/common/ApiResponse.java
  src/main/java/com/example/demo/common/ResponseMessage.java
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostBattleCandidateResponseDto.java
  src/main/java/com/example/demo/dto/post/PostCreateRequestDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindMusicGenreResponseDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostDetailFindResponseDto.java
  src/main/java/com/example/demo/dto/post/PostFindMusicResponseDto.java
  src/main/java/com/example/demo/dto/post/PostFindResponseDto.java
  src/main/java/com/example/demo/dto/post/PostsBattleCandidateResponseDto.java
  src/main/java/com/example/demo/dto/post/PostsFindResponseDto.java
  src/main/java/com/example/demo/model/post/Genre.java
  src/main/java/com/example/demo/model/post/Music.java
  src/main/java/com/example/demo/model/post/Post.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostFilteringCase.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/model/post/LikeTest.java
  src/test/java/com/example/demo/model/post/PostTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
  src/test/java/com/example/demo/service/PrincipalServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FEAT, TEST

#85 [FEAT] oauth2 로그인 기능 추가
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  build.gradle
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/example/demo/Application.java
  src/main/java/com/example/demo/config/AppProperties.java
  src/main/java/com/example/demo/config/SecurityConfig.java
  src/main/java/com/example/demo/config/WebMVcConfig.java
  src/main/java/com/example/demo/controller/GlobalControllerAdvice.java
  src/main/java/com/example/demo/model/member/Member.java
  src/main/java/com/example/demo/repository/MemberRepository.java
  src/main/java/com/example/demo/security/RestAuthenticationEntryPoint.java
  src/main/java/com/example/demo/security/TokenAuthenticationFilter.java
  src/main/java/com/example/demo/security/TokenProvider.java
  src/main/java/com/example/demo/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/example/demo/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/example/demo/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/example/demo/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/example/demo/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/example/demo/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/example/demo/service/MemberService.java
  src/main/java/com/example/demo/util/CookieUtils.java
  src/main/resources/application.yml
  src/test/java/com/example/demo/controller/HealthControllerTest.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllIntegrationTest.java
  src/test/java/com/example/demo/controller/genre/GenreAllRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberAllPostsRestDocsTest.java
  src/test/java/com/example/demo/controller/member/MemberDetailsRestDocsTest.java
  src/test/java/com/example/demo/model/member/MemberTest.java
Labels: 백엔드, sejun, FEAT

#97 [ADD] localhost:3000의 리다이렉트 url 뚫기, logback용 yml 속성 추가
  src/main/resources/application.yml
Labels: 리뷰 요청, 백엔드, sejun, ADD

#83 [CHORE] codecov에 코드 커버리지 적용되지 않는 문제
  build.gradle
Labels: 리뷰 요청, 백엔드, CHORE, suyoung

#100 [FIX] 음악 공유 게시글 등록: 중복된 유저 및 음악 url 예외 로직 추가
  src/main/java/com/example/demo/common/ExceptionMessage.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/repository/PostRepositoryTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: 리뷰 요청, 백엔드, sohyeon, FIX

#104 [FIX] 배틀 엔티티 장르,완료 여부 추가
  build.gradle
  src/main/java/com/example/demo/model/battle/Battle.java
  src/main/java/com/example/demo/model/battle/BattleStatus.java
  src/main/resources/db/migration/V2.1__Fix_Battle_is_ended.sql
  src/main/resources/db/migration/V2__Add_Battle_new_column.sql
  src/main/resources/logback-spring.xml
  src/test/java/com/example/demo/model/battle/BattleTest.java
Labels: 리뷰 요청, 백엔드, CHORE, suyoung
